# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - sistemabsensi

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: acrtelyu123.azurecr.io/
          username: ${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_932BD9B8FA974FEB92DB039C86368EB8 }}
          password: ${{ secrets.AZUREAPPSERVICE_CONTAINERPASSWORD_57066B40619245769BC10C167C1924FB }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: acrtelyu123.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_932BD9B8FA974FEB92DB039C86368EB8 }}/acrtelyu123/backend-absensi:${{ github.sha }}
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    needs: build
    
    steps:
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_354608AF07E24267A0427075ED087E64 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_2C4E064C50CA43B19073FFC6F178950E }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_57B60E45D2A84A11A50BA7C5F0D2E48B }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'sistemabsensi'
          slot-name: 'Production'
          images: 'acrtelyu123.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_932BD9B8FA974FEB92DB039C86368EB8 }}/acrtelyu123/backend-absensi:${{ github.sha }}'
          