# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - sistemabsensi

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: acrtelyu123.azurecr.io
          username: ${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_A9680F19ADC24A948C1308FF663D81BB }}
          password: ${{ secrets.AZUREAPPSERVICE_CONTAINERPASSWORD_925C540EF0B04934B67BB7583F1FE0B1 }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          context: ./backend-absensi
          push: true
          tags: acrtelyu123.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_A9680F19ADC24A948C1308FF663D81BB }}/backend-absensi:${{ github.sha }}
          file: ./backend-absensi/Dockerfile

  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # WAJIB ADA BUAT LOGIN AZURE V2
      contents: read
    
    needs: build
    
    steps:
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_995FB5A7B3184BE68EAED6792D1C330E }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_2DF5183DCD2541348DA060236B834E0F }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_0E6DEC0CA6584983818619A6FA6183B5 }}
        
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'sistemabsensi'
          slot-name: 'Production'
          images: 'acrtelyu123.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_A9680F19ADC24A948C1308FF663D81BB }}/backend-absensi:${{ github.sha }}'